---
### group_vars/DC1_FABRIC.yml

# Set the Fabric Name - must match an Ansible Inventroy Group
fabric_name: CAMPUS

# Set Design Type to L2ls
design:
  type: l2ls

# Spine Switches (L2 only)
l3spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: "65201"
    loopback_ipv4_pool: 192.168.0.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_peer_ipv4_pool: 192.168.1.0/24
    mlag_peer_l3_ipv4_pool: 192.168.2.0/24
    mlag_interfaces: [ Ethernet1, Ethernet2 ]
    virtual_router_mac_address: 00:1c:73:00:dc:00
  node_groups:
    SPLINE:
      nodes:
        SPL1:
          id: 1
          mgmt_ip: 172.100.100.101/24
        SPL2:
          id: 2
          mgmt_ip: 172.100.100.102/24

# Leaf Switches
leaf:
  defaults:
    platform: vEOS-LAB
    mlag_peer_ipv4_pool: 192.168.1.0/24
    uplink_switches: [SPL1, SPL2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384

  node_groups:
    FLOOR1:
      mlag: true
      filter:
        tags: [bluezone, greenzone]
      nodes:
        L2L1A:
          id: 1
          mgmt_ip: 172.100.100.105/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        L2L1B:
          id: 2
          mgmt_ip: 172.100.100.106/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
    FLOOR2:
      mlag: true
      filter:
        tags: [bluezone, orangezone]
      nodes:
        L2L2A:
          id: 3
          mgmt_ip: 172.100.100.107/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        L2L2B:
          id: 4
          mgmt_ip: 172.100.100.108/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6]

#### Override for vEOS/cEOS Lab Caveats ####
p2p_uplinks_mtu: 1500
