---
port_profiles:
  A_SERVER_10:
    mode: access
    vlans: 10
    spanning_tree_portfast: edge
  A_SERVER_11:
    mode: access
    vlans: 11
    spanning_tree_portfast: edge
  B_SERVER_10:
    mode: access
    vlans: 10
    spanning_tree_portfast: edge
  B_SERVER_11:
    mode: access
    vlans: 11
    spanning_tree_portfast: edge

servers:
  A_SERVER1:
    rack: A
    adapters:
    - endpoint_ports:
      - Ethernet1
      switch_ports:
      - Ethernet5
      switches:
      - L1A
  A_SERVER2:
    rack: A
    adapters:
    - endpoint_ports:
      - Ethernet1
      switch_ports:
      - Ethernet5
      switches:
      - L1B

  B_SERVER1:
    rack: B
    adapters:
    - endpoint_ports:
      - Ethernet1
      switch_ports:
      - Ethernet5
      switches:
      - L2A
  B_SERVER2:
    rack: B
    adapters:
    - endpoint_ports:
      - Ethernet1
      switch_ports:
      - Ethernet5
      switches:
      - L2B
