tenants:
  TENANT_A:
    mac_vrf_id_base: 10000
    mac_vrf_vni_base: 10000
    vrfs:
      A_VRF01:
        vrf_id: 1
        address_families:
          - vpn-ipv4
          - evpn
        svis:
          10:
            enabled: true
            name: A_DC_10
            ip_address_virtual: 10.0.10.1/24
            tags:
              - dc
          11:
            enabled: true
            name: A_DC_11
            ip_address_virtual: 10.0.11.1/24
            tags:
              - dc
          101:
            enabled: true
            name: A_CAMPUS_101
            ip_virtual_router_addresses:
              - 10.1.101.1
            nodes:
              SPL1:
                ip_address: 10.1.101.2/24
              SPL2:
                ip_address: 10.1.101.3/24
            tags:
              - campus
          102:
            enabled: true
            name: A_CAMPUS_102
            ip_virtual_router_addresses:
              - 10.1.102.1
            nodes:
              SPL1:
                ip_address: 10.1.102.2/24
              SPL2:
                ip_address: 10.1.102.3/24
            tags:
              - campus
        # Turn on tenant ospf for PE4/5
        ospf:
          enabled: true
          nodes: [ PE4, PE5, SPL1, SPL2 ]
        # L3 routed interfaces
        l3_interfaces:
          # WAN site1 connectivity
          - interfaces: [ Ethernet3.10, Ethernet4.10 ]
            enabled: true
            ip_addresses: [ 172.16.11.1/29, 172.16.11.2/29 ]
            nodes: [ PE1, PE2 ]
          # WAN site2 connectivity
          - interfaces: [ Ethernet2 ]
            enabled: true
            ip_addresses: [ 172.16.12.0/31 ]
            nodes: [ PE3 ]
          # WAN site3 (campus) PE interfaces
          - interfaces: [ Ethernet1.10, Ethernet2.10, Ethernet1.10, Ethernet2.10 ]
            enabled: true
            ip_addresses: [ 192.168.13.0/31, 192.168.13.2/31, 192.168.13.4/31, 192.168.13.6/31 ]
            nodes: [ PE4, PE4, PE5, PE5 ]
            ospf:
              enabled: true
          # WAN site3 (campus) SPL interfaces
          - interfaces: [ Ethernet5.10, Ethernet5.10, Ethernet6.10, Ethernet6.10 ]
            enabled: true
            ip_addresses: [ 192.168.13.1/31, 192.168.13.5/31, 192.168.13.7/31, 192.168.13.3/31 ]
            nodes: [ SPL1, SPL2, SPL1, SPL2 ]
            ospf:
              enabled: true
        # BGP peers
        172.16.12.1:
          enabled: true
          remote_as: 123
          nodes: [ PE3 ]
          description: ACPE2

  TENANT_B:
    mac_vrf_id_base: 20000
    mac_vrf_vni_base: 20000
    vrfs:
      B_VRF01:
        vrf_id: 101
        address_families:
          - vpn-ipv4
          - evpn
        svis:
          10:
            enabled: true
            name: B_DC_10
            ip_address_virtual: 10.0.10.1/24
            tags:
              - dc
          11:
            enabled: true
            name: B_DC_11
            ip_address_virtual: 10.0.11.1/24
            tags:
              - dc
          1101:
            enabled: true
            name: B_CAMPUS_1101
            ip_virtual_router_addresses:
              - 10.11.101.1
            nodes:
              SPL1:
                ip_address: 10.11.101.2/24
              SPL2:
                ip_address: 10.11.101.3/24
            tags:
              - campus
          1102:
            enabled: true
            name: B_CAMPUS_1102
            ip_virtual_router_addresses:
              - 10.11.102.1
            nodes:
              SPL1:
                ip_address: 10.11.102.2/24
              SPL2:
                ip_address: 10.11.102.3/24
            tags:
              - campus
        # Turn on tenant ospf for PE4/5
        ospf:
          enabled: true
          nodes: [ PE4, PE5, SPL1, SPL2 ]
        # L3 routed interfaces
        l3_interfaces:
          # WAN site1 connectivity
          - interfaces: [ Ethernet3.11, Ethernet4.11 ]
            enabled: true
            ip_addresses: [ 172.16.11.9/29, 172.16.11.10/29 ]
            nodes: [ PE1, PE2 ]
          # WAN site2 connectivity
          - interfaces: [ Ethernet4 ]
            enabled: true
            ip_addresses: [ 172.16.12.2/31 ]
            nodes: [ PE3 ]
          # WAN site3 (campus) PE interfaces
          - interfaces: [ Ethernet1.11, Ethernet2.11, Ethernet1.11, Ethernet2.11 ]
            enabled: true
            ip_addresses: [ 192.168.14.0/31, 192.168.14.2/31, 192.168.14.4/31, 192.168.14.6/31 ]
            nodes: [ PE4, PE4, PE5, PE5 ]
            ospf:
              enabled: true
          # WAN site3 (campus) SPL interfaces
          - interfaces: [ Ethernet7.11, Ethernet7.11, Ethernet8.11, Ethernet8.11 ]
            enabled: true
            ip_addresses: [ 192.168.14.1/31, 192.168.14.5/31, 192.168.14.7/31, 192.168.14.3/31 ]
            nodes: [ SPL1, SPL2, SPL1, SPL2 ]
            ospf:
              enabled: true
        # BGP peers
        172.16.12.3:
          enabled: true
          remote_as: 321
          nodes: [ PE3 ]
          description: BCPE2
