---
- name: Build Switch configuration
  hosts: DC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:
    - name: generate intended variables
      import_role:
        name: arista.avd.eos_designs

    # - name: Build a act topolgy
    #   import_role:
    #     name: arista.avd.act_topology_gen

    - name: generate device intended config and documentation
      import_role:
        name: arista.avd.eos_cli_config_gen

    - name: deploy configuration to device
      tags: [ deploy, never ]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
      # check_mode: true
