---
- name: Prep Ansible Host
  hosts: gitlab
  gather_facts: no
  tasks:

    # Update dnf cache
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes

    # Install postfix
    - name: Install postfix
      ansible.builtin.dnf:
        name: 'postfix'
        state: latest

    # Make sure postfix is started and enabled
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: postfix
        state: started
        enabled: yes

    # Install wget
    - name: Install wget
      ansible.builtin.yum:
        name: 'wget'
        state: latest

    # Install nano
    - name: Install nano
      ansible.builtin.yum:
        name: 'nano'
        state: latest

    # Get gitlab repo script
    - name: Download gitlab repo script
      ansible.builtin.get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
        dest: /home/cvpadmin/script.rpm.sh
        mode: '0775'

    # Run gitlab-reconfigure
    - name: Run gitlab-reconfigure
      ansible.builtin.shell: "os=el dist=8 ./script.rpm.sh"

    # Install gitlab-ce
    - name: Install gitlab-ce
      ansible.builtin.dnf:
        name: 'gitlab-ce'
        state: latest

    # Set gitlab external URL
    - name: Set gitlab external URL
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: '^# external_url'
        line: 'external_url "https://{{ ansible_host }}"'

    # Run gitlab-reconfigure
    - name: Run gitlab-reconfigure
      ansible.builtin.shell: "gitlab-ctl reconfigure"

    # Get gitlab initial password
    - name: Get gitlab initial password
      ansible.builtin.shell: cat /etc/gitlab/initial_root_password
      register: file_content

    - name: "Print the gitlab initial password"
      debug:
        msg: "{{ file_content.stdout }}"
