avd_fabric_defaults:
  fabric_local_as: 150
  # copies any settings from here to top level fabric file.
  fabric_name: NAUTOBOT_TEST_FABRIC
  custom_structured_configuration_ntp:
    local_interface:
      name: Management1
      vrf: MGMT
    servers:
      - name: 0.se.pool.ntp.org
        preferred: false
        vrf: MGMT
      - name: 1.se.pool.ntp.org
        preferred: true
        vrf: MGMT
  evpn_rd_type:
    admin_subfield: overlay_loopback
  evpn_rt_type:
    admin_subfield: 65000
  bgp_maximum_paths: 4
  bgp_ecmp: 4
  evpn_ebgp_multihop: 10
  evpn_prevent_readvertise_to_server: true
  bfd_multihop:
    interval: 10000
    min_rx: 10000
    multiplier: 3
  vxlan_vlan_aware_bundles: false
  custom_structured_configuration_switchport_default:
    mode: routed

# Name must match site name in nautobot
NAUTOBOT-DC1:
  dc_defaults:
  spine:
    defaults:
      loopback_ipv4_pool: 100.64.11.0/24
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
    nodes:
      dc1-spine1:
        bgp_as: 1234
      dc1-spine2:
        bgp_as: 1234
  l3leaf:
    defaults:
      virtual_router_mac_address: 00:1c:73:00:dc:00
      uplink_ipv4_pool: 100.64.10.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.64.11.0/24
      vtep_loopback_ipv4_pool: 100.64.12.0/24
      mlag_peer_l3_ipv4_pool: 100.64.13.0/24
      mlag_peer_ipv4_pool: 100.64.14.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
      uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ Ethernet53/1, Ethernet54/1 ]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
    node_groups:
      dc1-leaf1:
        nodes:
          dc1-leaf1a:
            uplink_switch_interfaces: [Ethernet1, Ethernet1]
            uplink_switches: [ dc1-spine1, dc1-spine2 ]
          dc1-leaf1b:
            uplink_switch_interfaces: [Ethernet2, Ethernet2]
            uplink_switches: [ dc1-spine1, dc1-spine2 ]
      dc1-leaf2:
        nodes:
          dc1-leaf2a:
            uplink_switch_interfaces: [Ethernet3, Ethernet3]
            uplink_switches: [ dc1-spine1, dc1-spine2 ]
          dc1-leaf2b:
            uplink_switch_interfaces: [Ethernet4, Ethernet4]
            uplink_switches: [ dc1-spine1, dc1-spine2 ]


